version: '0.2.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\Glob" -c %CONFIGURATION% --no-dependencies
after_build:
- dotnet pack "src\Glob" -c %CONFIGURATION% --no-build -o ..\..\artifacts
test_script:
- dotnet test test\Glob.Tests\Glob.Tests.csproj -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'